### ISSUE TITLE
Docs request

### ISSUE THREAD

**Issue by OliverM** [pitch-io/uix#103]
**Is your feature request related to a problem? Please describe.**
The beta react docs suggest starting new projects with integrated stacks like Remix or Next.js. Is there an equivalent set of Clojure backend libraries UIx2 recommends or relies on? Not necessarily equivalent in terms of convention over configuration, just in terms of functionality for SSR support, etc. 

I'd like to see something like this in the docs but no worries if there's nothing specific to say here.

**Describe the solution you'd like**
Some tips/suggestions 😉 

**Describe alternatives you've considered**
Going with the tried and true choices I'm familiar with, but maybe there's the opportunity to learn something new

**Comment by roman01la** [comment]
AFAIK there's nothing like Next.js and co in Clojure world. Are you looking for purely local development stack to produce static websites and/or dynamic content with UIx? If that's the case, I can only recommend to go with traditional Clojure stack, which is Ring server and then add UIx code in there to render on JVM and/or on the client. Does that sound like what you are looking for?

Otherwise, AFAIK there's nothing like Next.js in Clojure world as in "the platform" for deploying and intelligently serving React-based websites. Although I _think_ it should be possible to integrate UIx into Next.js or similar frameworks, but of course it's only client side part of the stack.

**Comment by OliverM** [comment]
I can default to the normal Ring-based setup. I've used remix a bit durning excursions into non-clojure stacks and like the convention it has around routes and http verbs over explicit configuration, on top of the close React integration. But it's something that could be introduced as a project-level convention. Thanks for the response!
